[phases.setup]
nixPkgs = ["...", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci --include-workspace-root --workspace=backend --workspace=shared"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
